Restore compatibility with python 3.9
